# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.CharField(default='kalady', max_length=50),
        ),
    ]
