# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0003_news_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
