# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0004_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinned_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossapp.News')),
            ],
        ),
    ]
