# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0005_pinned_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='average',
            field=models.FloatField(default=0.0),
        ),
    ]
