# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0009_auto_20170419_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fossapp.UserProfile'),
        ),
    ]
