# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0011_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='downvoted',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvoted', to='fossapp.News'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upvoted',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted', to='fossapp.News'),
        ),
    ]
