# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0012_auto_20170419_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='fossapp.Category'),
        ),
    ]
