# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fossapp', '0013_auto_20170419_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fossapp.UserProfile'),
        ),
    ]
